# Generated by Django 3.2 on 2024-07-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='month_birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'month_birthday',
            },
        ),
        migrations.CreateModel(
            name='birthday_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('day', models.CharField(blank=True, max_length=64, null=True)),
                ('line', models.CharField(blank=True, max_length=64, null=True)),
                ('client', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('observation', models.CharField(blank=True, max_length=64, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.month_birthday')),
            ],
            options={
                'db_table': 'birthday_list',
            },
        ),
    ]
