# Generated by Django 3.2 on 2024-12-12 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bindBonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.CharField(max_length=50)),
                ('bidding', models.CharField(max_length=50)),
                ('numBond', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('disponible', 'Disponible'), ('redimido', 'Redimido')], default='disponible', max_length=30)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bindBonds',
            },
        ),
    ]
