# Generated by Django 3.2 on 2024-12-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bindbonds_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindbonds',
            name='numBond',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bindbonds',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
