# Generated by Django 3.2 on 2024-12-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bindbonds_redemptiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindbonds',
            name='numBond',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
