# Generated by Django 3.2 on 2024-12-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_bindbonds_numbond'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bindbonds',
            constraint=models.UniqueConstraint(fields=('numBond', 'idCard'), name='unique_numBond_idCard'),
        ),
    ]
