# Generated by Django 3.2 on 2024-12-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_bindbonds_unique_numbond_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindbonds',
            name='numBond',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
